-- SELECT 1 AS TEST;
-- INSERT INTO car (brand, model, production_year, actual_daily_price) VALUES ('toyota', 'yaris', '2023', 100);
-- INSERT INTO _user (first_name, last_name, phone_number, address, email, password, role) values ('Tom', 'Smith', '123456789', 'Warsaw', 'tom@gmail.com', 'zaq1', 'CUSTOMER');
-- INSERT INTO customer (user_id) VALUES (1L);